[build-system]
build-backend = "poetry.masonry.api"
requires = ["poetry>=1.0.0"]

[tool.black]
exclude = "{{cookiecutter.project_name}}/*"
line-length = 80

[tool.poetry]
authors = ["Macklan Weinstein <wolfgangwazzlestrauss@gmail.com>"]
description = "Python project template for scaffolding."
homepage = "https://github.com/wolfgangwazzlestrauss/scaffold-python"
keywords = []
license = "MIT"
name = "scaffold-python"
readme = "README.md"
version = "0.0.1"

[tool.poetry.dependencies]
python = "^3.6.1"

[tool.poetry.dev-dependencies]
black = "^19.10b0"
flake8 = "^3.7.9"
flake8-bugbear = "^20.1.4"
flake8-docstrings = "^1.5.0"
flake8-import-order = "^0.18.1"
mccabe = "^0.6.1"
mkdocs = "^1.1"
mkdocs-material = "^5.4.0"
mypy = "^0.770"
pre-commit = "^2.3.0"
pymdown-extensions = "^7.1"
pytest = "^5.4.2"
pytest-cookies = "^0.5.1"
pytest-mock = "^3.1.0"
typer = "^0.2.1"
