# Python configuration file for building, dependencies, and tooling.
#
# For more information, visit
# https://snarky.ca/what-the-heck-is-pyproject-toml/.

[build-system]
build-backend = "hatchling.build"
requires = ["hatchling~=1.0"]

[dependency-groups]
dev = [
    "mkdocs~=1.6",
    "mkdocs-material~=9.6",
    "mypy~=1.15",
    "pymdown-extensions~=10.15",
    "pytest~=8.3",
    "pytest-cookies~=0.7.0",
    "pytest-mock~=3.14",
    "ruff~=0.11.0",
    "types-toml~=0.10.0",
]

[project]
authors = [{ email = "macklan.weinstein@gmail.com", name = "Macklan Weinstein" }]
description = "Python project template for scaffolding."
keywords = []
license = "MIT"
name = "scaffold-python"
readme = "README.md"
requires-python = "~=3.9"
version = "0.2.1"

[tool.mypy]
check_untyped_defs = true
disallow_untyped_calls = false
disallow_untyped_defs = true
exclude = [
    '\.benchmarks/',
    '\.cache/',
    '\.hypothesis/',
    '\.pytest_cache/',
    '\.ruff_cache/',
    '\.venv/',
    'tmp/',
    '\{\{cookiecutter.project_name\}\}/',
]
ignore_missing_imports = true
no_implicit_optional = true
strict_optional = true
warn_redundant_casts = true
warn_return_any = true
warn_unused_ignores = true

[tool.pytest.ini_options]
addopts = "-sv"
# python_files = ["*.test.py"]
python_classes = "Test*"
python_files = [
    "__init__.py",
    "test_*.py",
]
python_functions = ["test_*"]
testpaths = ["test"]

[tool.ruff]
extend-exclude = ["[{][{]cookiecutter.project_name[}][}]"]

[tool.uv]
package = false
