# Python dependency, build, and

[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core>=1.0.0"]

[tool.black]
exclude = "{{cookiecutter.project_name}}/*"
line-length = 80

[tool.poetry]
authors = ["Macklan Weinstein <wolfgangwazzlestrauss@gmail.com>"]
description = "Python project template for scaffolding."
homepage = "https://github.com/wolfgangwazzlestrauss/scaffold-python"
keywords = []
license = "MIT"
name = "scaffold-python"
readme = "README.md"
version = "0.0.2"

[tool.poetry.dependencies]
python = "^3.6.1"

[tool.poetry.dev-dependencies]
black = "^20.8b1"
flake8 = "^3.9.0"
flake8-bugbear = "^21.3.2"
flake8-docstrings = "^1.5.0"
flake8-import-order = "^0.18.1"
mccabe = "^0.6.1"
mkdocs = "^1.1.2"
mkdocs-material = "^7.0.6"
mypy = "^0.812"
pymdown-extensions = "^8.1.1"
pytest = "^5.4.3"
pytest-cookies = "^0.5.1"
pytest-mock = "^3.5.1"
