# Python configuration file for building, dependencies, and tooling.
#
# For more information, visit
# https://snarky.ca/what-the-heck-is-pyproject-toml/.

[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core>=1.0.0"]

[tool.black]
extend-exclude = "{{cookiecutter.project_name}}/*"
line-length = 80

[tool.poetry]
authors = ["Macklan Weinstein <wolfgangwazzlestrauss@gmail.com>"]
description = "Python project template for scaffolding."
homepage = "https://github.com/wolfgangwazzlestrauss/scaffold-python"
keywords = []
license = "MIT"
name = "scaffold-python"
readme = "README.md"
version = "0.1.0"

[tool.poetry.dependencies]
python = "^3.6.2"

[tool.poetry.dev-dependencies]
black = "^21.9b0"
flake8 = "^4.0.0"
flake8-bugbear = "^21.9.0"
flake8-docstrings = "^1.6.0"
flake8-import-order = "^0.18.0"
mccabe = "^0.6.1"
mkdocs = "^1.2.0"
mkdocs-material = "^7.3.0"
mypy = "^0.910"
pdbpp = "^0.10.3"
pymdown-extensions = "^9.0.0"
pytest = "^6.2.0"
pytest-cookies = "^0.6.0"
pytest-mock = "^3.6.0"
