name: publish
on:
  push:
    tags:
    - v[0-9]+.[0-9]+.[0-9]+
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: Code repository checkout
      uses: actions/checkout@v1
    - name: Install Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install poetry
        poetry install
    - name: Build package
      run: |
        poetry build
    - name: Publish package to PyPI
      uses: pypa/gh-action-pypi-publish@master
      with:
        user: __token__
        password: {{ "${{ secrets.pypi_password }}" }}
