image: "python:3.8"
stages:
- test
- deploy
before_script:
- python -m pip install --upgrade pip
- python -m pip install poetry
- poetry install
test:
  stage: test
  script:
  - poetry run tox -e doc
  - poetry run tox -e format
  - poetry run tox -e lint
  - poetry run tox -e py37
pages:
  stage: deploy
  script:
  - poetry run mkdocs build
  artifacts:
    paths:
    - public
  only:
    master
