tasks:
  - init: |
      python3 -m pip install --user poetry
      POETRY_VIRTUALENVS_IN_PROJECT=1 poetry export --dev --without-hashes -f requirements.txt -o requirements.txt
      python3 -m pip install --user --progress-bar off -r requirements.txt .
