image: "python:3.6"
stages:
- test
- deploy
before_script:
- python -m pip install --upgrade pip
- python -m pip install poetry
- poetry install
test:
  stage: test
  script:
  - poetry run tox -e static
  - poetry run tox -e py36
pages:
  stage: deploy
  script:
  - poetry run mkdocs build
  artifacts:
    paths:
    - site
  only:
    master
