# Pre-commit, https://pre-commit.com/, configuration file for Git hooks.
#
# To initialize hooks within a Git repository, execute pre-commit install.

repos:
  - repo: https://github.com/ambv/black
    rev: 20.08b1
    hooks:
      - id: black
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
      - id: flake8
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.761
    hooks:
      - id: mypy
  {%- if cookiecutter.prettier_support == "yes" -%}
  - repo: https://github.com/prettier/prettier
    rev: "1.19.1"
    hooks:
      - id: prettier
  {%- endif -%}
