copyright: Copyright &copy; 2020 {{ cookiecutter.author_name }}
extra:
  social:
    - icon: fontawesome/brands/{{ cookiecutter.githost }}
      link: https://{{ cookiecutter.githost }}.com/{{ cookiecutter.githost_username }}
    - icon: fontawesome/solid/envelope
      link: mailto://{{ cookiecutter.author_email }}
extra_css:
  - css/style.css
extra_javascript:
  - https://unpkg.com/mermaid@8.8.1/dist/mermaid.min.js
  - js/index.js
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
      linenums: true
  - footnotes
  - meta
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - toc:
      permalink: true
nav:
  - Home: index.md
  - User Guide: src/user/index.md
  - API Reference: src/reference/index.md
  - Developer Guide: src/developer/index.md
plugins:
  - mkdocstrings
  - search
repo_name: {{ cookiecutter.project_name }}
repo_url: {{ cookiecutter.project_repopage }}
site_author: {{ cookiecutter.author_name }}
site_description: |
  {{ cookiecutter.project_description }}
site_name: {{ cookiecutter.project_name }}
site_url: {{ cookiecutter.project_docpage }}
theme:
  featues:
    - navigation.tabs
  name: material
  palette:
    accent: cyan
    primary: teal
