copyright: Copyright &copy; 2020 {{ cookiecutter.author_name }}
extra:
  social:
    - type: home
      link: https://wolfgangwazzlestrauss.com
    - type: github
      link: https://{{ cookiecutter.git_host }}.com/{{ cookiecutter.git_username }}
    - type: inbox
      link: mailto://{{ cookiecutter.author_email }}
extra_css:
  - css/termynal.css
extra_javascript:
  - js/mermaid.min.js
  - js/termynal.js
  - js/index.js
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
      linenums: true
  - footnotes
  - meta
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - toc:
      permalink: true
nav:
  - Home: index.md
  - Command Line: src/cli/index.md
  - User Guide: src/user/index.md
  - API Reference: src/reference/index.md
  - Developer Guide: src/developer/index.md
plugins:
  - mkdocstrings
  - search
repo_name: {{ cookiecutter.project_name }}
repo_url: {{ cookiecutter.project_homepage }}
site_author: {{ cookiecutter.author_name }}
site_description: |
  {{ cookiecutter.project_homepage }}
site_name: {{ cookiecutter.project_name }}
site_url: https://wolfgangwazzlestrauss.github.io/yamltable/index
theme:
  favicon: img/favicon.ico
  logo: img/favicon.ico
  name: material
  palette:
    accent: cyan
    primary: teal
