[build-system]
build-backend = "poetry.masonry.api"
requires = ["poetry>=1.0.0"]

[tool.black]
line-length = 80

[tool.coverage.report]
exclude_lines = [
    "if sys.version_info.*",
    "pragma: no cover",
    "raise NotImplementedError",
]
fail_under = 100
show_missing = true

[tool.coverage.run]
branch = true
command_line = "-m pytest"
omit = []
source = ["{{ cookiecutter.project_slug }}"]

[tool.poetry]
authors = ["{{ cookiecutter.author_name }} <{{ cookiecutter.author_email }}>"]
description = "{{ cookiecutter.project_description }}"
documentation = "{{ cookiecutter.project_docpage }}"
homepage = "{{ cookiecutter.project_repopage }}"
keywords = []
{% if cookiecutter.license != "MIT" -%}
license = "MIT"
{%- endif %}
name = "{{ cookiecutter.project_name }}"
readme = "README.md"
version = "{{ cookiecutter.project_version }}"

[tool.poetry.dependencies]
python = "^3.6.1"
{% if cookiecutter.cli_support == "yes" -%}
typer = "^0.2.1"
{%- endif %}
typing-extensions = "^3.7.4.2"

[tool.poetry.dev-dependencies]
bandit = "^1.6.2"
black = "^19.10b0"
coverage = { version = "^5.2.1", extras = ["toml"] }
flake8 = "^3.8.3"
flake8-bugbear = "^20.1.4"
flake8-docstrings = "^1.5.0"
flake8-import-order = "^0.18.1"
mccabe = "^0.6.1"
mkdocs = "^1.1.2"
mkdocs-material = "^5.5.6"
mkdocstrings = "^0.12.2"
mypy = "^0.782"
pre-commit = "^2.6.0"
py-spy = "^0.3.3"
pymdown-extensions = "^7.1"
pytest = "^5.4.3"
pytest-cov = "^2.10.0"
pytest-mock = "^3.2.0"
toml = "^0.10.1"
tox = "^3.19.0"
{% if cookiecutter.cli_support == "yes" -%}
typer-cli = "^0.0.9"

[tool.poetry.scripts]
{{ cookiecutter.project_name }} = "{{ cookiecutter.project_slug }}.__main__:app"
{% endif -%}
