# Python configuration file for building, dependencies, and tooling.
#
# For more information, visit
# https://snarky.ca/what-the-heck-is-pyproject-toml/.

[build-system]
build-backend = "hatchling.build"
requires = ["hatchling~=1.0"]

[dependency-groups]
dev = [
    "coverage[toml]~=7.6.0",
    "mkdocs~=1.6",
    "mkdocs-material~=9.6",
    "mkdocstrings~=0.29.0",
    "mypy~=1.15",
    "pymdown-extensions~=10.15",
    "pytest~=8.3",
    "pytest-cov~=6.1",
    "pytest-mock~=3.14",
    "ruff~=0.11.0",
    "toml~=0.10.0",
    "types-toml~=0.10.0",
]

[project]
authors = [{ email = "{{ cookiecutter.author_email }}", name = "{{ cookiecutter.author_name }}" }]
{%- if cookiecutter.cli_support == "yes" %}
dependencies = [
    "typer~=0.15.0",
]
{%- else %}
dependencies = []
{%- endif %}
description = "{{ cookiecutter.project_description }}"
documentation = "{{ cookiecutter.project_homepage }}"
keywords = []
{%- if cookiecutter.license == "MIT" %}
license = "MIT"
{%- endif %}
name = "{{ cookiecutter.project_name }}"
readme = "README.md"
requires-python = "~=3.9"
version = "{{ cookiecutter.project_version }}"

{% if cookiecutter.cli_support == "yes" -%}
[project.scripts]
{{ cookiecutter.project_name }} = "{{ cookiecutter.project_slug }}.__main__:app"
{% endif -%}

[tool.coverage.report]
exclude_lines = [
    "if sys.version_info.*",
    "pragma: no cover",
    "raise NotImplementedError",
]
fail_under = 100
show_missing = true

[tool.coverage.run]
branch = true
command_line = "-m pytest"
omit = []
source = ["{{ cookiecutter.project_slug }}"]

[tool.hatch.build.targets.wheel]
packages = ["src/{{ cookiecutter.project_slug }}"]

[tool.mypy]
cache_dir = ".cache/mypy"
check_untyped_defs = true
disallow_untyped_calls = false
disallow_untyped_defs = true
exclude = [
    '\.benchmarks/',
    '\.cache/',
    '\.hypothesis/',
    '\.pytest_cache/',
    '\.ruff_cache/',
    '\.venv/',
    'tmp/',
]
ignore_missing_imports = true
no_implicit_optional = true
strict_optional = true
warn_redundant_casts = true
warn_return_any = true
warn_unused_ignores = true

[tool.pytest.ini_options]
addopts = "-sv"
cache_dir = ".cache/pytest"
markers = [
    "e2e: mark as end to end test.",
    "unit: mark as unit test.",
]
python_files = ["__init__.py", "*_test.py"]
testpaths = ["src", "test"]

[tool.ruff]
cache-dir = ".cache/ruff"
