[build-system]
build-backend = "poetry.masonry.api"
requires = ["poetry>=0.12"]

[tool.black]
line-length = 80

[tool.coverage.report]
exclude_lines = [
    "raise NotImplementedError",
    "if sys.version_info.*"
]
fail_under = 100
show_missing = true

[tool.coverage.run]
branch = true
command_line = "-m pytest"
omit = []
source = ["{{ cookiecutter.project_slug }}"]

[tool.poetry]
authors = ["{{ cookiecutter.author_name }} <{{ cookiecutter.author_email }}>"]
description = "{{ cookiecutter.project_description }}"
homepage = "{{ cookiecutter.project_homepage }}"
keywords = []
license = "MIT"
name = "{{ cookiecutter.project_name }}"
readme = "README.md"
version = "{{ cookiecutter.project_version }}"

[tool.poetry.dependencies]
python = "^3.6.1"
{% if "cli" in cookiecutter.features -%}
typer = "^0.0.11"
{%- endif %}
typing-extensions = "^3.7.4"

[tool.poetry.dev-dependencies]
bandit = "^1.6.2"
black = "^19.10b0"
coverage = { version = "^5.0.1", extras = ["toml"] }
flake8 = "^3.7.9"
mkdocs = "^1.1"
mkdocs-material = "^4.6.3"
mkdocstrings = "^0.8.0"
mypy = "^0.761"
pre-commit = "^1.21.0"
pymdown-extensions = "^6.3"
pytest = "^5.2"
pytest-cov = "^2.8.1"
pytest-mock = "^2.0.0"
pytest-testmon = "^1.0.2"
pytest-xdist = "^1.31.0"
toml = "^0.10.0"
tox = "^3.14.3"
{% if "cli" in cookiecutter.features -%}
typer-cli = "^0.0.6"
{%- endif %}

{%- if "cli" in cookiecutter.features %}
[tool.poetry.scripts]
{{ cookiecutter.project_name }} = "{{ cookiecutter.project_slug }}.__main__:app"
{% endif -%}
