# GitHub Actions workflow to build and test code.
#
# For a reference of workflow file syntax, see
# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions.

name: build
on:
  push:
    branches:
      - develop
      - feature/*
      - master
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code repository
        uses: actions/checkout@v2
      {%- if cookiecutter.prettier_support == "yes" %}
      - name: Install Node interpreter
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Install Node dependencies
        run: |
          npm install
      - name: Static lint configuration files
        run: |
          npm run lint-test
      {% endif -%}
      - name: Install Python interpreter
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install tox
      - name: Static lint code
        run: |
          tox -e lint
  build:
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        python: [3.6, 3.7, 3.8, 3.9]
    runs-on: {{ "${{ matrix.os }}" }}
    steps:
      - name: Checkout code repository
        uses: actions/checkout@v2
      - name: Install Python interpreter
        uses: actions/setup-python@v2
        with:
          python-version: {{ "${{ matrix.python }}" }}
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install tox
      - name: Build and test code
        run: |
          tox -e py
