name: build
on:
  push:
    branches:
      - develop
      - feature/*
      - master
jobs:
  static:
    runs-on: ubuntu-latest
    steps:
      - name: Code repository checkout
        uses: actions/checkout@v2
      {%- if cookiecutter.prettier_support == "yes" %}
      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Install Node dependencies
        run: |
          npm install
      - name: Check format of configuration files
        run: |
          npm run lint
      {% endif -%}
      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install tox
      - name: Build and static test with tox
        run: |
          tox -e static
  test:
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        python: [3.6, 3.7, 3.8]
    runs-on: {{ "${{ matrix.os }}" }}
    steps:
      - name: Code repository checkout
        uses: actions/checkout@v2
      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: {{ "${{ matrix.python }}" }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install tox
      - name: Build and test with tox
        run: |
          tox -e py
