# GitHub Actions workflow file.
#
# For more information, visit
# https://docs.github.com/actions/learn-github-actions.

name: release

# Make workflow run only for pushed SemVer compatible tags.
on:
  push:
    tags:
      - "v?[0-9]+.[0-9]+.[0-9]+"

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code repository
        uses: actions/checkout@v2
      - name: Install Python interpreter
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install Python packages
        run: |
          python -m pip install --upgrade pip poetry setuptools wheel
          poetry config virtualenvs.in-project true
          poetry install -v
      - name: Build package
        run: poetry build
      - name: Upload package to PyPI
        uses: pypa/gh-action-pypi-publish@v1
        with:
          user: __token__
          password: {{ "${{ secrets.PYPI_PASSWORD }}" }}
