# GitHub Actions workflow file.
#
# For more information, visit
# https://docs.github.com/actions/learn-github-actions.

---
name: release

# Makes workflow run on Git tag.
on:
  push:
    tags:
      - "**"
  workflow_dispatch:
    inputs:
      debug:
        default: false
        description: Use Tmate session for debugging
        type: boolean

jobs:
  release:
    name: Get Git tag and make GitHub release
    runs-on: ubuntu-latest
    outputs:
      tag: {% raw -%} ${{ steps.extract_tag.outputs.tag }} {%- endraw %}
      upload_url: {% raw -%}  ${{ steps.create_release.outputs.upload_url }} {%- endraw %}
    steps:
      - name: Extract tag
        id: extract_tag
        shell: bash
        run: echo "##[set-output name=tag;]$(echo ${GITHUB_REF#refs/tags/})"
      - name: Checkout code repository
        uses: actions/checkout@v3
      - name: Create GitHub release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: {% raw -%} ${{ secrets.GITHUB_TOKEN }} {%- endraw %}
        with:
          tag_name: {% raw -%} ${{ github.ref }} {%- endraw %}
          release_name: {{ cookiecutter.project_name }} {% raw -%} ${{ steps.extract_tag.outputs.tag }} {%- endraw %}
          body: >-
            See the
            [changelog]({{ cookiecutter.project_repository }}/blob/{% raw -%} ${{
            steps.extract_tag.outputs.tag }} {%- endraw %}/CHANGELOG.md) for more information.
      - name: Setup Tmate session if debug enabled
        if: >-
          {% raw -%} ${{ always() && github.event_name == 'workflow_dispatch' &&
          inputs.debug }} {%- endraw %}
        timeout-minutes: 60
        uses: mxschmitt/action-tmate@v3
{% if cookiecutter.pypi_support == "yes" %}
  package:
    name: Build and publish Python package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code repository
        uses: actions/checkout@v3
      - name: Install Python interpreter
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install Python packages
        run: |
          python --version
          python -m pip --version
          python -m pip install poetry
          poetry install --no-dev
      - name: Build Python package
        run: poetry build
      - name: Upload package to GitHub release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: {% raw -%} ${{ secrets.GITHUB_TOKEN }} {%- endraw %}
        with:
          upload_url: {% raw -%} ${{ steps.create_release.outputs.upload_url }} {%- endraw %}
          asset_path: >-
            dist/{{ cookiecutter.project_slug }} {%- raw -%} -${{ steps.extract_tag.outputs.tag
            }}-py3-none-any.whl {%- endraw %}
          asset_name: >-
            {{ cookiecutter.project_slug }} {%- raw -%} -${{ steps.extract_tag.outputs.tag
            }}-py3-none-any.whl {%- endraw %}
          asset_content_type: application/octet-stream
      # Use PyPI publish action over Poetry publish to prevent PyPI password
      # from being printed in CI logs.
      - name: Upload package to PyPI
        uses: pypa/gh-action-pypi-publish@v1
        with:
          user: __token__
          password: {% raw -%} ${{ secrets.PYPI_PASSWORD }} {%- endraw %}
      - name: Setup Tmate session if debug enabled
        if: >-
          {% raw -%} ${{ always() && github.event_name == 'workflow_dispatch' &&
          inputs.debug }} {%- endraw %}
        timeout-minutes: 60
        uses: mxschmitt/action-tmate@v3
{% endif -%}
