# GitHub Actions workflow file.
#
# For more information, visit
# https://docs.github.com/actions/learn-github-actions.

---
name: release

# Makes workflow run on Git tag.
on:
  push:
    tags:
      - "**"
  workflow_dispatch:
    inputs:
      debug:
        default: false
        description: Use Tmate session for debugging
        type: boolean

jobs:
  release:
    name: Make GitHub release and publish Python package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code repository
        uses: actions/checkout@v3
      - name: Install Python interpreter
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install Python packages
        run: |
          python --version
          python -m pip --version
          python -m pip install poetry
          poetry install --no-dev
      - name: Build Python package
        run: poetry build
      - name: Create GitHub release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          body: >-
            See the
            [changelog]({{ cookiecutter.project_repository }}/blob/{% raw -%} ${{
            steps.extract_tag.outputs.tag }} {%- endraw %}/CHANGELOG.md) for more information.
          files: >-
            dist/{{ cookiecutter.project_slug }} {%- raw -%} -${{ github.ref_name }}-py3-none-any.whl {%- endraw %}
          name: {{ cookiecutter.project_name }} {% raw -%} ${{ github.ref_name }} {%- endraw %}
          tag_name: {% raw -%} ${{ github.ref }} {%- endraw %}
      {% if cookiecutter.pypi_support == "yes" -%}
      # Use PyPI publish action over Poetry publish to prevent PyPI password
      # from being printed in CI logs.
      - name: Upload package to PyPI
        uses: pypa/gh-action-pypi-publish@v1
        with:
          user: __token__
          password: {% raw -%} ${{ secrets.PYPI_PASSWORD }} {%- endraw %}
      {% endif -%}
      - name: Setup Tmate session if debug enabled
        if: >-
          {% raw -%} ${{ always() && github.event_name == 'workflow_dispatch' &&
          inputs.debug }} {%- endraw %}
        timeout-minutes: 60
        uses: mxschmitt/action-tmate@v3
