# GitHub Actions workflow file.
#
# For more information, visit
# https://docs.github.com/actions/learn-github-actions.

---
name: test

# Makes workflow run on push or pull request to the main or develop branches.
on:
  pull_request:
    branches:
      - develop
      - main
  push:
    branches:
      - develop
      - main
  workflow_dispatch:
    inputs:
      debug:
        default: "false"
        description: Use TMate session for debugging on failure
        required: false

jobs:
  test:
    name: {% raw -%} Run test suite for Python ${{ matrix.python }} on ${{ matrix.os }} {%- endraw %}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        python: ["3.8", "3.9", "3.10", "3.11"]
    runs-on: {% raw -%} ${{ matrix.os }} {%- endraw %}
    steps:
      - name: Checkout code repository
        uses: actions/checkout@v3
      - name: Install Python interpreter
        uses: actions/setup-python@v4
        with:
          python-version: {% raw -%} ${{ matrix.python }} {%- endraw %}
      - name: Cache Python packages
        uses: actions/cache@v3
        with:
          path: .venv
          key: >-
            {% raw -%} python-${{ matrix.python }}_${{ runner.os }}_poetry-${{
            hashFiles('poetry.lock') }} {%- endraw %}
      - name: Install Python packages
        run: |
          python --version
          python -m pip --version
          python -m pip install poetry
          poetry config virtualenvs.in-project true
          poetry install --verbose
      - name: Run test suite
        run: poetry run pytest --cov
      - name: Setup tmate session if job failed
        if: >-
          {% raw -%} ${{ failure() && github.event_name == 'workflow_dispatch' &&
          github.event.inputs.debug == 'true' }} {%- endraw %}
        timeout-minutes: 60
        uses: mxschmitt/action-tmate@v3
