# GitHub Actions workflow to build and test code.
#
# For a reference of workflow file syntax, see
# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions.

name: build
on:
  push:
    branches:
      - develop
      - feature/*
      - master
jobs:
  lint:
     name: Run linter tests on project files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code repository
        uses: actions/checkout@v2
      - name: Install Node interpreter
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Install Prettier formatter
        run: npm install -g prettier
      - name: Check configuration file formatting
        run: prettier --check .
      - name: Install Python interpreter
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip poetry setuptools wheel
          poetry install -v
      - name: Static lint code
        run: |
          poetry run black --check .
          poetry run flake8 hooks/ tests/
          poetry run mypy hooks/ tests/
          mkdir docs \
            && cp README.md docs/index.md \
            && poetry run mkdocs build --strict

  build:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        python: [3.6, 3.7, 3.8, 3.9]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code repository
        uses: actions/checkout@v2
      - name: Install Python interpreter
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip poetry setuptools wheel
          poetry install -v
      - name: Build and test code
        run: poetry run pytest
