# GitHub Actions workflow file.
#
# For more information, visit
# https://docs.github.com/actions/learn-github-actions.

name: build

# Make workflow run only for commits pushed or pull requests made to the
# develop, main, and master branches.
on:
  push:
    branches:
      - develop
      - main
      - master
  pull_request:
    branches:
      - develop
      - main
      - master

jobs:
  lint:
    name: Check code with formatter and linter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code repository
        uses: actions/checkout@v2
      - name: Install Node interpreter
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Install Prettier formatter
        run: npm install -g prettier
      - name: Check configuration file formatting
        run: prettier --check .
      - name: Install Python interpreter
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Cache Python packages
        uses: actions/cache@v2
        with:
          path: .venv
          key: python-3.9_ubuntu-latest_poetry-${{ hashFiles('poetry.lock') }}
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip poetry setuptools wheel
          poetry config virtualenvs.in-project true
          poetry install -v
      - name: Static lint code
        run: |
          poetry run black --check .
          poetry run flake8 hooks/ tests/
          poetry run mypy hooks/ tests/
          mkdir docs \
            && cp README.md docs/index.md \
            && poetry run mkdocs build --strict

  test:
    name: Run test suite for ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        python: [3.6, 3.7, 3.8, 3.9]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code repository
        uses: actions/checkout@v2
      - name: Install Node interpreter
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Install Prettier formatter
        run: npm install -g prettier
      - name: Install Python interpreter
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Cache Python packages
        uses: actions/cache@v2
        with:
          path: .venv
          key: >-
            python-${{ matrix.python }}_${{ matrix.os }}_poetry-${{
            hashFiles('poetry.lock') }}
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip poetry setuptools wheel
          poetry config virtualenvs.in-project true
          poetry install -v
      - name: Build and test code
        run: poetry run pytest
