name: build
on:
  push:
    branches:
    - develop
    - feature/*
    - master
jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        python: [3.6, 3.7, 3.8]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Code repository checkout
      uses: actions/checkout@v1
    - name: Install Python
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install poetry
        poetry install -v
    - name: Build and test with tox
      run: |
        poetry run tox -e format
        poetry run tox -e py
