# GitHub Actions workflow to build and test code.
#
# For a reference of workflow file syntax, see
# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions.

name: build
on:
  push:
    branches:
      - develop
      - feature/*
      - master
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code repository
        uses: actions/checkout@v2
      - name: Install Node interpreter
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Install Node dependencies
        run: |
          npm install
      - name: Static lint configuration files
        run: |
          npm run lint-test
      - name: Install Python interpreter
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install poetry
          poetry install -v
      - name: Static lint code
        run: |
          poetry run black --check .
          poetry run flake8 hooks/ tests/
          poetry run mypy hooks/ tests/
          mkdir docs \
            && cp README.md docs/index.md \
            && poetry run mkdocs build --strict
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        python: [3.6, 3.7, 3.8, 3.9]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code repository
        uses: actions/checkout@v2
      - name: Install Python interpreter
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install poetry
          poetry install -v
      - name: Build and test code
        run: |
          poetry run pytest
